data: # root path of train/validation data (either relative/absoulte path is ok)
  train: 'train'
  validation: 'valid'
  mel_path: 'mels'

train:
  rep_discriminator: 1
  discriminator_train_start_steps: 200000
  num_workers: 8
  batch_size: 16
  optimizer: 'adam'
  adam:
    lr: 0.00002
    beta1: 0.5
    beta2: 0.9

audio:
  n_mel_channels: 80
  segment_length: 16000
  pad_short: 2000
  filter_length: 2048
  hop_length: 600 
  win_length: 2048
  sampling_rate: 48000
  mel_fmax: 11025.0
  mel_fmin: 20.0

model:
  feat_match: 10.0
  lambda_adv: 2.5
  lambda_time_loss: 20
  use_subband_stft_loss: False
  feat_loss: False
  out_channels: 1
  generator_ratio: [10, 10, 6] # for 600 hop size and 48000 sample rate
  mult: 256
  n_residual_layers: 4
  num_D : 3
  ndf : 16
  n_layers: 3
  downsampling_factor: 4
  disc_out: 512

time_loss_params:
  win_lengths: [1, 240, 480, 960]
  hop_sizes: [1, 120, 240, 480]
  window: "hann_window"

stft_loss_params:
    fft_sizes: [1024, 2048, 512]  # List of FFT size for STFT-based loss.
    hop_sizes: [120, 240, 50]     # List of hop size for STFT-based loss
    win_lengths: [600, 1200, 240] # List of window length for STFT-based loss.
    window: "hann_window"         # Window function for STFT-based loss
subband_stft_loss_params:
  fft_sizes: [384, 683, 171]  # List of FFT size for STFT-based loss.
  hop_sizes: [30, 60, 10]     # List of hop size for STFT-based loss
  win_lengths: [150, 300, 60] # List of window length for STFT-based loss.
  window: "hann_window"       # Window function for STFT-based loss


log:
  summary_interval: 2
  validation_interval: 5
  save_interval: 20
  chkpt_dir: 'train1/chkpt'
  log_dir: 'train1/logs'
